# ==========================================
# PREPARE BASE MODEL PARAMS (Architecture)
# ==========================================
IMAGE_SIZE: [224, 224, 3]
WEIGHTS: imagenet
INCLUDE_TOP: False
POOLING: avg
CLASSES: 4
LEARNING_RATE: 0.0001

# ADD THESE for the new training/stacking logic
DROPOUT: 0.3
TRAIN_VAL_SPLIT: 0.2
BATCH_SIZE: 16

# ... (rest of the training/stacking params)

# ==========================================
# TRAINING PARAMS (Separated by Model)
# ==========================================
# You can give each model different settings if they train differently!

DenseNet121:
  EPOCHS: 20
  AUGMENTATION: True

ResNet50:
  EPOCHS: 25
  AUGMENTATION: True

EfficientNetB0:
  EPOCHS: 30
  AUGMENTATION: True
